### ISSUE TITLE
Doesn't pluralize "process" correctly

### ISSUE THREAD

**Issue by leonsp** [zealot128/ruby-habtm-generator#1]
This:
rails g habtm chef_process chef_script

Generates:
db/migrate/20140508165135_create_chef_proces_chef_scripts.rb

Expected:
db/migrate/20140508165135_create_chef_processes_chef_scripts.rb

The same issue affects the table name, index name, and so on.

Thanks,

Leo

**Comment by zealot128** [comment]
Sorry for the late answer.

Meanwhile, the pluralization should work better. Also, with v.0.5, now common table prefix ("chef" in your example) are supported (#4).

I've added your model names as a new "test case".
