### ISSUE TITLE
naming convention on tables with common prefix

### ISSUE THREAD

**Issue by fredwillmore** [zealot128/ruby-habtm-generator#4]
As of rails 4: 
If your tables share a common prefix, it will only appear once at the beginning. For example, the tables “catalog_categories” and “catalog_products” generate a join table name of “catalog_categories_products”.

http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_and_belongs_to_many

**Comment by zealot128** [comment]
Thanks. I wasn't aware of that convention. I've stolen the Rails join table name generation code and released 0.5
