### ISSUE TITLE
Rails 5 support and schema plus

### ISSUE THREAD

**Issue by gregorbarth** [zealot128/ruby-habtm-generator#5]
It seems the syntax for habtm-migrations changed. While I had no trouble with this gem before, after switching to rails 5 and the newest schema plus, the generated habtm migrations won't migrate.
If the syntax of the current rails guide is used, everything works again.

Old syntax generated by gem:
class CreateFacilitiesPupils < ActiveRecord::Migration
  def change
    create_table :facilities_pupils, :id => false do |t|
      t.references :facility, :pupil
    end
     #index stuff here
  end
end

class CreateFacilitiesPupils < ActiveRecord::Migration
  def change
    create_table :facilities_pupils, id: false do |t|
      t.references :facilities
      t.references :pupils
    end
     #index stuff here
  end
end

Maybe this can be fixed for the current version. Everything else seems fine.

Thanks,
Gregor

**Comment by zealot128** [comment]
Sounds good! 

As you already pointed out the way to fix it, do you might to want to contribute the fix as a Pull Request?

**Comment by gregorbarth** [comment]
Am 13.11.2015 um 15:12 schrieb Stefan Wienert:
> Sounds good!
> 
> As you already pointed out the way to fix it, do you might to want to
> contribute the fix as a Pull Request?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zealot128/ruby-habtm-generator/issues/5#issuecomment-156442717>.
> 
Sure, I'll look into it.
